### ISSUE TITLE
Small issue with post types on ultra-narrow browser window

### ISSUE THREAD

**Issue by korymath** [nmec/p2-responsive#4]
I am really loving responsive P2... finding and tracking some small bugs so that we can work toward fixing them...

![capture](https://f.cloud.github.com/assets/178099/1545432/535830da-4d76-11e3-97b9-d1c32e130624.JPG)

Check the screenshot...

**Comment by korymath** [comment]
Some potential fixes for smaller screens... 

``` csss
#postbox input#tags {
    width: 68%
}

#post-types {
width: 100%;
}
```

**Comment by nmec** [comment]
What browser/version is this affecting?

**Comment by korymath** [comment]
Sorry I missed this so long ago. Cleaning up cruft now. Best of luck.
